In [ ]:
# 반복문 없이 데이터 배열에 대한 처리를 지원함함

In [ ]:
conda install numpy # 미니콘다만

# Numpy - Numerical Pyton

## 1. ndarrary(Numpy Dimensional Arrary)

In [2]:
# de facto standard
import numpy as np

In [5]:
a = np.array([1,4,5,8], float) # array( [] ,타입)
print(a) #리스트에서는 콤마 붙지만 여기서는 안붙음

[1. 4. 5. 8.]


In [6]:
# a의 인덱싱

a[3], a.dtype, a.shape

#shape 
# 1차원 (5,) tuple로 표현 a.shape -> (4,)
# 

(8.0, dtype('float64'), (4,))

In [ ]:
# 넘파이는 하나의 데이터 타입만 배열에 넣을 수 있음 
# 배열생성 ndarray

## 2. Array shape

In [15]:
# 1차원 - vector
a = np.array([1,4,5,8], float) # array( [] ,타입)
a

array([1., 4., 5., 8.])

In [17]:
# 2차원 - matrix
m = [[1,4],[5,8]]
b = np.array(m, float)
print(b)

[[1. 4.]
 [5. 8.]]


In [4]:
# 3차원 - tensor
t =  [[[1,4],[5,8]], [[11,14],[15,18]]]
c = np.array(t,float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [25]:
# ndim 
a.ndim, b.ndim, c.ndim 

(1, 2, 3)

In [23]:
# size #element의 개수
a.size, b.size, c.size
#element의 갯수가 몇개냐?

(4, 4, 8)

In [5]:
# data type(dtype)
c = np.array(t,dtype=np.float32)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]], dtype=float32)

- reshape: size는 동일

In [7]:
c.reshape(2,4).shape

(2, 4)

In [8]:
c.reshape(8,) #1차원으로 주르륵 나옴 #element의 갯수는 변하지 않음 

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

In [10]:
c.reshape(-1,4) #끝에를 4개로 맞춰놓으면 나머지는 -1로 그러면 shape이 2가됨 

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [12]:
# flatten - 1차원으로 변환
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

## 3. Indexing and Slicing

In [15]:
a = np.arange(6) # a = np.arrange(6)  #에이레인지
a

array([0, 1, 2, 3, 4, 5])

In [17]:
a = np.arange(6).reshape(2,3) #2차원으로 한방에 
a

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
a[0][1], a[0,1]  # 행 인덱스, 열 인덱스 

(1, 1)

In [20]:
#넘파이는 2차원도 행과 열에 대한 슬라이싱이 가능 

a[:, :2]

array([[0, 1],
       [3, 4]])

In [21]:
b= np.arange(16).reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
# 5,6,9,10

b[ 1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [26]:
# 0,1,4,5,8,9

b[ :3  ,:2 ] #열 #행 

array([[0, 1],
       [4, 5],
       [8, 9]])

In [27]:
# 세번째 열까지는 x, 마지막 열은 y
X, Y = b[ : , :-1 ], b[:,-1]
X.shape, Y.shape

((4, 3), (4,))

## 4. Creation

In [30]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,2.2,0.1) #넘파이에서는 실수를 소수점으로 가능 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1])

In [32]:
np.arange(0,2.2,0.1).tolist() #리스트로 만들수있음 

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3,
 1.4000000000000001,
 1.5,
 1.6,
 1.7000000000000002,
 1.8,
 1.9000000000000001,
 2.0,
 2.1]

In [33]:
# 실수는 우리가 원하는 값을 정확하게 표현하지 못함
np.arange(0,2.2,0.1).tolist()[3] == 0.3 #0.3이냐 물으면 false 나옴

False

In [34]:
# 두 실수의 비교는 차이가 아주 작냐를 물어보는 것이 올바른 방법임
np.abs(np.arange(0,2.2,0.1).tolist()[3] - 0.3) <1e-8 #10-8승보다 작냐라고 물으면 True 그 얘기는 즉, 같냐고 묻는거와 같음 

True

In [35]:
# ones, zeros, empty
a = np.zeros((5,), dtype =np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [44]:
b = np.zeros((2,4), dtype =np.int8)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [46]:
np.empty((2,5)) #empty 할당 zeros 할당&초기화 

array([[9.49410842e-312, 1.77863633e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [9.68247409e-071, 2.14331753e+184, 6.25789088e-091,
        6.74934131e-067, 8.32220097e-315]])

In [47]:
a = np.arange(24).reshape(4,-1)
np.ones_like(a)

#4*6 모양 크기는 24대로 

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [49]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [50]:
# 단위행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 행렬곱 dot product

[[1,2,3 ]] * [4]
             [5]
             [6]
(1,3)       (3,1)

# 3자리와 3자리의 값이 같을 때 계산 가능 결과는 (1,1) 1*4 + 2*5 + 3*6 =32 [[32]]

#### Y=w*x+b  #weight bias dot matrix

In [ ]:
# eye - 대각선이 1인 행렬   
np.eye(3,5)

In [53]:
np.eye(N=3,M=5,k=-1) # 대각선으로

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [ ]:
np.eye(3,5,2)

- random sampling

In [55]:
np.random.seed(2021)

#균등분포
np.random.uniform(0,1,10).reshape(2,5)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [ ]:
#정규분포
np.random.normal(0,1,10).reshape(2,5) #normal 정규분포

In [56]:
#이항분포, 포아송분포, t-분포(standard-t), F-분포
np.random.binomial(100, 1/6., 10)

array([12, 11, 24, 18, 12, 17, 18, 24, 17, 15])