In [1]:
import numpy as np

#### 1번 넘파이를 사용하여 행렬을 만드시오

In [7]:
m= [[10, 20,30,40], [50,60,70,80]]
a = np.array(m, float)
print(a)

[[10. 20. 30. 40.]
 [50. 60. 70. 80.]]


In [ ]:
np.arange(1,9).reshape(2*4)

#### 2번

In [9]:
m = np.array([[ 0, 1, 2, 3, 4],
              [ 5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [52]:
# 1) 이 행렬에서 값 7 을 인덱싱한다.
print(m[1,2])
# 2) 이 행렬에서 값 14 을 인덱싱한다.
print(m[2,4]) # = -1,-1
# 3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1:2,1:3] #[1,1:3]

7
14


array([[6, 7]])

In [37]:
# 4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:3,2:3] #[1:.2]

array([[ 7],
       [12]])

In [63]:
# 5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2,3:5]

array([[3, 4],
       [8, 9]])

#### 3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.

In [51]:
m = np.array([[ 0, 1, 2, 3, 4],
              [ 5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

f = m.reshape(-1,)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
# 1) 이 배열에서 3의 배수를 찾아라.
f[f% 3 == 0 ]

array([ 0,  3,  6,  9, 12])

In [53]:
# 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
f[f % 4 ==1]

array([ 1,  5,  9, 13])

In [54]:
# 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
f[f%3 == 0 and f%4 ==1]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# f[np.logical_and

#### 4. 값을 입력하지말고 행렬을 만들어라 

In [79]:
np.eye(5,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

#### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.

In [27]:
#전체의 최댓값
ran.max()

10

In [18]:
#각 행의 합
ran.sum(axis=1)

array([27, 27, 40, 38, 24])

In [23]:
#각 열의 평균
ran. mean(axis =0)

array([6.4, 5. , 3.8, 2.6, 6.4, 7. ])

In [25]:
# 각 열의 최솟값
ran.min(axis=0)

array([3, 0, 1, 0, 3, 5])

#### 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.

In [36]:
eng= np.array([[ 1, 2, 3, 4],
            [ 46, 99, 100, 71],
            [ 81, 59, 90, 100]])

In [40]:
# 3 2 4 1 
print(np.sort(eng))


[[  1   2   3   4]
 [ 46  71  99 100]
 [ 59  81  90 100]]


In [ ]:
argsort(score[1]) 1번째줄 기준으로 sort 

In [ ]:
# 내림차순 한꺼번에 수행 
score[:,np.argsort(score[1])[::-1]]

#### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [2]:
np.random.seed(5)
dice = np.random.randint(1,7,100)
dice.mean()

3.48

#### 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [ ]:
N(0,1)

전일 9900 10000+(-1)*0.01 *10000
9900+(1)*0.01 *9900 =9999

In [ ]:
# arry 계산은 빠름 하지만 갯수를 줄이거나 늘리는건 어령ㅁ
# list 계산은 느리지만 갯수를 줄이거나 늘리는건 쉬움 